#ifndef CRONCOIN_CHAINPARAMSSEEDS_H
#define CRONCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the croncoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {};
static const uint8_t chainparams_seed_test[] = {};
static const uint8_t chainparams_seed_testnet4[] = {};
static const uint8_t chainparams_seed_signet[] = {};

#endif // CRONCOIN_CHAINPARAMSSEEDS_H
